# Data Preparation

In [1]:
import pandas as pd

df_employee_attrition = pd.read_csv("../../data/raw/HR-Employee-Attrition.csv", sep=",", encoding="utf-8")

df_employee_attrition

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [2]:
rows, columns = df_employee_attrition.shape
print(f'\nLinhas: {rows}\nColunas: {columns}')

Linhas: 1470
Colunas: 35

In [3]:
df_employee_attrition.columns.to_list()

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'Over18',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [4]:
df_employee_attrition.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

In [5]:
df_employee_attrition.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [6]:
df_employee_attrition.describe(include=object)

/var/folders/r3/xkff0rhn7wq73n6y30813qvc0000gn/T/ipykernel_85067/4211518411.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_employee_attrition.describe(include=object)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
count,1470,1470,1470,1470,1470,1470,1470,1470,1470
unique,2,3,3,6,2,9,3,1,2
top,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Y,No
freq,1233,1043,961,606,882,326,673,1470,1054

In [7]:
df_employee_attrition.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [8]:
df_employee_attrition.duplicated().sum()

np.int64(0)

In [9]:
categorical_col = df_employee_attrition.select_dtypes(include=object).columns.to_list()

for col in categorical_col:
    print(f'\n{df_employee_attrition[col].value_counts()}')

Attrition
No     1233
Yes     237
Name: count, dtype: int64

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

Gender
Male      882
Female    588
Name: count, dtype: int64

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

Over18
Y    1470
Name: count, dtype: int64

OverTime
No     1054
Yes     416
Name: count, dtype: int64

/var/folders/r3/xkff0rhn7wq73n6y30813qvc0000gn/T/ipykernel_85067/776435857.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_col = df_employee_attrition.select_dtypes(include=object).columns.to_list()

In [10]:
df_employee_attrition["AttritionFlag"] = df_employee_attrition["Attrition"].map({
        "Yes": 1,
        "No": 0
    })

attrition_rate = df_employee_attrition["AttritionFlag"].mean()

print(f'Taxa de Turnover: {attrition_rate:.2%}')

Taxa de Turnover: 16.12%

In [11]:
df_employee_attrition["AgeGroup"] = pd.cut(
    df_employee_attrition["Age"],
    bins=[17, 25, 35, 45, 55, 65],
    labels=["18-25", "26-35", "36-45", "46-55", "56-65"]
)

df_employee_attrition["TenureGroup"] = pd.cut(
    df_employee_attrition["YearsAtCompany"],
    bins=[-1, 1, 3, 5, 10, 40],
    labels=["0-1", "2-3", "4-5", "6-10", "10+"]
)

df_employee_attrition["DistanceGroup"] = pd.cut(
    df_employee_attrition["DistanceFromHome"],
    bins=[0, 5, 10, 20, 30],
    labels=["0-5", "6-10", "11-20", "21-30"],
    include_lowest=True
)

df_employee_attrition["CareerStage"] = pd.cut(
    df_employee_attrition["TotalWorkingYears"],
    bins=[-1, 2, 5, 10, 20, 40],
    labels=["Entry-level", "Early career", "Mid career", "Experienced", "Late career"]
)

df_employee_attrition["RoleStabilityGroup"] = pd.cut(
    df_employee_attrition["YearsInCurrentRole"],
    bins=[-1, 1, 3, 7, 20],
    labels=["0-1", "2-3", "4-7", "8+"]
)

df_employee_attrition["PromotionDelayGroup"] = pd.cut(
    df_employee_attrition["YearsSinceLastPromotion"],
    bins=[-1, 0, 2, 5, 15],
    labels=["Promoted this year", "1-2 years", "3-5 years", "5+ years"]
)

df_employee_attrition["IncomeGroup"] = pd.cut(
    df_employee_attrition["MonthlyIncome"],
    bins=[0, 3000, 6000, 10000, 20000],
    labels=["Low", "Medium", "High", "Very High"]
)


education_map = {
    1: "Below College",
    2: "College",
    3: "Bachelor",
    4: "Master",
    5: "Doctor"
}

satisfaction_map = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}

performance_rating_map = {
    1: "Low",
    2: "Good",
    3: "Excellent",
    4: "Outstanding"
}

work_life_balance_map = {
    1: "Bad",
    2: "Good",
    3: "Better",
    4: "Best"
}


df_employee_attrition["EducationLevel"] = (
    df_employee_attrition["Education"].map(education_map)
)

df_employee_attrition["StockOption"] = df_employee_attrition["StockOptionLevel"].map(
    {
        0: "No Options",
        1: "Low",
        2: "Medium",
        3: "High"
    }
)

df_employee_attrition["JobLevelGroup"] = df_employee_attrition["JobLevel"].map(
    {
        1: "Entry Level",
        2: "Junior Level",
        3: "Mid Level",
        4: "Senior Level",
        5: "Executive Level"
    }
)

df_employee_attrition["SatisfactionLevel"] = (
    df_employee_attrition["JobSatisfaction"].map(satisfaction_map)
)

df_employee_attrition["PerformanceRatingLevel"] = (
    df_employee_attrition["PerformanceRating"].map(performance_rating_map)
)

df_employee_attrition["EnvironmentSatisfactionLevel"] = (
    df_employee_attrition["EnvironmentSatisfaction"].map(satisfaction_map)
)

df_employee_attrition["JobInvolvementLevel"] = (
    df_employee_attrition["JobInvolvement"].map(satisfaction_map)
)

df_employee_attrition["RelationshipSatisfactionLevel"] = (
    df_employee_attrition["RelationshipSatisfaction"].map(satisfaction_map)
)

df_employee_attrition["WorkLifeBalanceLevel"] = (
    df_employee_attrition["WorkLifeBalance"].map(work_life_balance_map)
)

In [12]:
mapped_columns = [
    "EducationLevel",
    "StockOption",
    "JobLevelGroup",
    "SatisfactionLevel",
    "PerformanceRatingLevel",
    "EnvironmentSatisfactionLevel",
    "JobInvolvementLevel",
    "RelationshipSatisfactionLevel",
    "WorkLifeBalanceLevel"
]

df_employee_attrition[mapped_columns].isna().sum()

EducationLevel                   0
StockOption                      0
JobLevelGroup                    0
SatisfactionLevel                0
PerformanceRatingLevel           0
EnvironmentSatisfactionLevel     0
JobInvolvementLevel              0
RelationshipSatisfactionLevel    0
WorkLifeBalanceLevel             0
dtype: int64

In [13]:
df_employee_attrition.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'AttritionFlag', 'AgeGroup', 'TenureGroup',
       'DistanceGroup', 'CareerStage', 'RoleStabilityGroup',
       'PromotionDelayGroup', 'IncomeGroup', 'EducationLevel', 'StockOption',
       'JobLevelGroup', 'SatisfactionLevel', 'PerformanceRatingLevel',
       'EnvironmentSatisfactionLevel', 'JobInvolvementLevel',
       'RelationshipSatisfactionLevel', 'WorkLifeBalanceLevel'],
      dtype='str')

In [14]:
new_features = [
    'AgeGroup', 'IncomeGroup', 'TenureGroup', 'DistanceGroup', 'CareerStage', 
    'RoleStabilityGroup', 'PromotionDelayGroup', 'SatisfactionLevel', 'WorkLifeBalanceLevel',
    'JobLevelGroup', "EducationLevel", "EnvironmentSatisfactionLevel", "JobInvolvementLevel",
    "RelationshipSatisfactionLevel", "StockOption", "PerformanceRatingLevel"
    ]

for col in new_features:
    print(f'\n{df_employee_attrition[col].value_counts()}')

AgeGroup
26-35    606
36-45    468
46-55    226
18-25    123
56-65     47
Name: count, dtype: int64

IncomeGroup
Medium       519
Low          395
Very High    281
High         275
Name: count, dtype: int64

TenureGroup
6-10    448
4-5     306
2-3     255
10+     246
0-1     215
Name: count, dtype: int64

DistanceGroup
0-5      632
6-10     394
11-20    240
21-30    204
Name: count, dtype: int64

CareerStage
Mid career      607
Experienced     340
Late career     207
Early career    193
Entry-level     123
Name: count, dtype: int64

RoleStabilityGroup
2-3    507
4-7    399
0-1    301
8+     263
Name: count, dtype: int64

PromotionDelayGroup
Promoted this year    581
1-2 years             516
5+ years              215
3-5 years             158
Name: count, dtype: int64

SatisfactionLevel
Very High    459
High         442
Low          289
Medium       280
Name: count, dtype: int64

WorkLifeBalanceLevel
Better    893
Good      344
Best      153
Bad        80
Name: count, dtype: int64

JobLevelGroup
Entry Level        543
Junior Level       534
Mid Level          218
Senior Level       106
Executive Level     69
Name: count, dtype: int64

EducationLevel
Bachelor         572
Master           398
College          282
Below College    170
Doctor            48
Name: count, dtype: int64

EnvironmentSatisfactionLevel
High         453
Very High    446
Medium       287
Low          284
Name: count, dtype: int64

JobInvolvementLevel
High         868
Medium       375
Very High    144
Low           83
Name: count, dtype: int64

RelationshipSatisfactionLevel
High         459
Very High    432
Medium       303
Low          276
Name: count, dtype: int64

StockOption
No Options    631
Low           596
Medium        158
High           85
Name: count, dtype: int64

PerformanceRatingLevel
Excellent      1244
Outstanding     226
Name: count, dtype: int64

In [15]:
df_employee_attrition = df_employee_attrition.drop(columns=[
    "JobSatisfaction", "WorkLifeBalance", "JobLevel", "Education", "EnvironmentSatisfaction", "JobInvolvement", "RelationshipSatisfaction",
    "StockOptionLevel", "PerformanceRating"
    ])

In [16]:
df_employee_attrition.to_csv("../../data/clean/Employee-Attrition_Clean.csv", sep=",", encoding="utf-8", index=False)